# Generated by Django 2.1.5 on 2019-01-12 22:27

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='data',
            field=django.contrib.postgres.fields.jsonb.JSONField(default=''),
        ),
    ]
