# Generated by Django 2.1.5 on 2019-01-19 20:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weather', '0010_auto_20190119_1949'),
    ]

    operations = [
        migrations.AlterField(
            model_name='city',
            name='name',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
